# Generated by Django 6.1 on 2026-09-07 12:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('tile_pack', models.FileField(upload_to='map_packs/tiles/')),
                ('road_graph', models.FileField(upload_to='map_packs/graphs/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_size_mb', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlackoutZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('TUNNEL', 'Tunnel'), ('UNDERPASS', 'Underpass'), ('PARKING', 'Underground Parking'), ('URBAN_CANYON', 'Urban Canyon')], max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('approx_length_meters', models.FloatField()),
                ('entry_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('exit_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_zones', to='maps.mapregion')),
            ],
        ),
    ]
