# Generated by Django 6.1 on 2026-09-07 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('two_wheeler', 'Two Wheeler')], max_length=20)),
                ('mount_type', models.CharField(choices=[('dashboard_mount', 'Dashboard Mount'), ('pocket', 'Pocket')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_meters', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_detected', models.BooleanField(default=False)),
                ('outage_duration_seconds', models.FloatField(default=0.0)),
                ('distance_in_outage_meters', models.FloatField(default=0.0)),
                ('measured_drift_meters', models.FloatField(default=0.0)),
                ('drift_percentage', models.FloatField(default=0.0)),
                ('benchmark_passed', models.BooleanField(default=False)),
                ('trajectory_sample', models.JSONField(default=list)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telemetry.tripsession')),
            ],
        ),
    ]
